#!/bin/sh

UNAME="$(uname -a)"
case "$UNAME" in
    *Microsoft*) echo "wsl1";;
    *microsoft*) echo "wsl2";;
    *MINGW64*) echo "MINGW64";;
    *CYGWIN*) echo "CYGWIN";;
    *)
        CHASSIS="$(hostnamectl | grep Chassis | tr -s ' ' | cut -d' ' -f3)"
        if [[ $CHASSIS =~ vm ]]; then
            echo "virtualmachine"
        else
            echo "native"
        fi
esac
