#!/usr/bin/env python3

import os
import sys

def ec_update_file_with_fragment(target_file, fragment_file):
    '''
    Insert the content of the file fragment_file into the file target_file between two comment tags.
    The directory containing target_file and the file fragment_file must exist.
    If target_file does not exist, it is created.
    If it does not already contain the tags they are added at the end with the fragment between them.
    
    Limitation: only one fragment can be added.
    '''
    if not os.path.exists(os.path.dirname(target_file)) and os.path.dirname(target_file) != '':
        print(f"Target file directory {os.path.dirname(target_file)} does not exist")
        return 1
    if not os.path.isfile(fragment_file):
        print(f"Fragment file {fragment_file} does not exist")
        return 1

    with open(fragment_file, 'r') as f:
        fragment_text = f.read()

    tag_begin = "# EC_ADDITION_BEGIN"
    tag_end = "# EC_ADDITION_END"
    found_begin = False
    found_end = False
    in_block = False
    new_lines = []

    if os.path.exists(target_file):
        with open(target_file, 'r') as f:
            lines = f.readlines()

        for line in lines:
            if tag_begin in line:
                new_lines.append(line)
                new_lines.append('\n' + fragment_text + '\n')
                found_begin = True
                in_block = True
            elif tag_end in line:
                new_lines.append(line)
                found_end = True
                in_block = False
            elif not in_block:
                new_lines.append(line)

        if found_begin and not found_end:
            new_lines = [line for line in new_lines if tag_begin not in line and tag_end not in line]

    if not found_begin or not found_end:
        new_lines.append(f"\n{tag_begin}\n\n{fragment_text}\n{tag_end}\n")

    with open(target_file, 'w') as f:
        f.writelines(new_lines)

    return 0

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: insert_fragment_in_file <target_file> <fragment_file>")
        sys.exit(1)

    sys.exit(ec_update_file_with_fragment(target_file=sys.argv[1], fragment_file=sys.argv[2]))
