version: "3.8"
services:

  ec-base:
    build:
      context: .
    devices:
    - "/dev/fuse:/dev/fuse"
    cap_add:
    - "SYS_ADMIN"
    volumes:
    - type: bind
      source: ../
      target: /env-config
    working_dir: /env-config

  ec-ubuntu-base:
    extends:
      service: ec-base
    build:
      dockerfile: ubuntu.dockerfile

  ec-ubuntu-latest:
    extends:
      service: ec-ubuntu-base
    build:
      args:
        UBUNTU_VERSION: "latest"

  ec-ubuntu2604:
    extends:
      service: ec-ubuntu-base
    build:
      args:
        UBUNTU_VERSION: "26.04"

  ec-ubuntu2404:
    extends:
      service: ec-ubuntu-base
    build:
      args:
        UBUNTU_VERSION: "24.04"

  ec-ubuntu2204:
    extends:
      service: ec-ubuntu-base
    build:
      args:
        UBUNTU_VERSION: "22.04"

  ec-ubuntu2004:
    extends:
      service: ec-ubuntu-base
    build:
      args:
        UBUNTU_VERSION: "20.04"

  ec-ubuntu1804:
    extends:
      service: ec-ubuntu-base
    build:
      args:
        UBUNTU_VERSION: "18.04"

  ec-fedora-base:
    extends:
      service: ec-base
    build:
      dockerfile: fedora.dockerfile

  ec-fedora-latest:
    extends:
      service: ec-fedora-base
    build:
      args:
        FEDORA_VERSION: "latest"
