version: "3.8"
services:

  ec-ubuntu-base-full:
    build:
      context: .
    devices:
    - "/dev/fuse:/dev/fuse"
    cap_add:
    - "SYS_ADMIN"
    volumes:
    - type: bind
      source: ../
      target: /env-config
    working_dir: /env-config

  ec-ubuntu2404:
    extends:
      service: ec-ubuntu-base-full
    build:
      args:
        UBUNTU_VERSION: "24.04"

  ec-ubuntu2204:
    extends:
      service: ec-ubuntu-base-full
    build:
      args:
        UBUNTU_VERSION: "22.04"

  ec-ubuntu2004:
    extends:
      service: ec-ubuntu-base-full
    build:
      args:
        UBUNTU_VERSION: "20.04"

  ec-ubuntu1804:
    extends:
      service: ec-ubuntu-base-full
    build:
      args:
        UBUNTU_VERSION: "18.04"
