#!/usr/bin/env bash

readonly repo="$1"
readonly pattern="$2"

readonly urls=(
    $(wget -qO- "https://api.github.com/repos/$repo/releases/latest" \
        | jq -r --arg pattern "$pattern" \
            '.assets[] | select(.name | test($pattern)) | .browser_download_url')
)

case ${#urls[@]} in
    0) ec_log E "No matching GitHub release artifact found for 'bat'"; return 1;;
    1) ;;
    *) ec_log E "Multiple matching GitHub release artifacts found for 'bat'"; return 1;;
esac

if [[ -f "$D/$(basename $urls)" ]]; then
    ec_log N "Reusing cached artifact '$(basename $urls)'"
else
    wget --directory-prefix="$D" --no-verbose --show-progress --timestamping "$urls"
fi
